GET https://striveschool-api.herokuapp.com/books

#####

POST http://localhost:3030/books HTTP/1.1
content-type: application/json

  {
    "asin": "0987575422",
    "title": "The Battle of Evernight - Special Edition: The Bitterbynde Book #3 (The Bitterbynde Trilogy)",
    "img": "https://images-na.ssl-images-amazon.com/images/I/51vw%2Bn7xZCL.jpg",
    "price": 9.6,
    "category": "scifi"
  }
  
#####

PATCH http://localhost:3030/books/64088f44f4397b16dd790bb5
content-type: application/json

{
    "title": "Pandemic (The Extinction Files, Book 2",
    "category": "new generation"
}

#####

DELETE http://localhost:3030/books/6408a8e4d98fe62ce04d6881/


#####

GET http://localhost:3030/books/bytitle/

#####

GET http://localhost:3030/books/


#####

POST http://localhost:3030/authors HTTP/1.1
Content-Type: application/json

{
  "nome": "Mario",
  "cognome": "Rossi",
  "email": "mario.bramucci@gmail.com",
  "birthdate": "02/11/1971",
  "avatar": "https://ui-avatars.com/api/?name=Mario+Rossi"
}

#####

PATCH http://localhost:3030/authors/640a3b545a42babd656a6602
content-type: application/json

{
  "nome": "Pippo",
  "cognome": "Plutos",
  "email": "pippo.plutos@gmail.com",
  "birthdate": "09/11/1982",
  "avatar": "https://ui-avatars.com/api/?name=Pippo+Pluto"
}

#####

DELETE http://localhost:3030/authors/640a3e5fdaa811d5abdf8118

#####

GET http://localhost:4040/BlogPosts

#####

POST  http://localhost:4040/BlogPosts/ HTTP/1.1
Content-Type: application/json

{
"category": "PRova",
"title": "L'iPhon migliore di sempre",
"cover": "https://m.media-amazon.com/images/W/IMAGERENDERING_521856-T1/images/I/61XO4bORHUL._AC_SL1500_.jpg",
"readTime":{
  "value": "4",
  "unit": "minuti"

},
"author": {
  "name": "Carlo Cracco",
  "avatar": "https://ui-avatars.com/api/?name=Carlo+Cracco"
},
"content": "HTML"
}

#####

GET  http://localhost:3030/BlogPosts/640f73d9399ee1c323208acd

#####

PATCH http://localhost:4040/BlogPosts/641206f5db32a284b81fc8fb
content-type: application/json

{
# "category": "TECH",
# "title": "Il Nuovo Samsung Galaxy S23 è una bomba!",
# "cover": "https://www.elettrofuturo.it/wp-content/uploads/2023/02/Samsung-Galaxy-S23-Verde.png",
# "readTime":{
#   "time": "5",
#   "unit": "minuti"

# },
"author": {
"id": "003",
  "name": "Armando Calandrelli",
  "avatar": "https://ui-avatars.com/api/?name=Armando+Calandrelli"
}
# "content": "Oppo Find N2 Flip è indubbiamente uno degli smartphone <a più avanzati e completi disponibili sul mercato, grazie alla ricca dotazione e all'elevata multimedialità. Dispone di un grande display da <b>6.8</b> pollici con una risoluzione di <b>2520x1080</b> pixel. Le funzionalità offerte da questo Oppo Find N2 Flip sono veramente tante e all'avanguardia. A cominciare dal modulo <b>5G</b> che permette un trasferimento dati e una navigazione in internet eccellente. <br>Questo Oppo Find N2 Flip è un prodotto con pochi competitor per ciò che riguarda la multimedialità grazie alla fotocamera da ben <b>50</b> megapixel che permette al Oppo Find N2 Flip di scattare foto di alta qualità con una risoluzione di <b>8165x6124</b> pixel e di registrare video in <b>4K</b> alla risoluzione di <b>3840x2160</b> pixel. Lo spessore di <b>7.5mm</b> è veramente contenuto e rende questo Oppo Find N2 Flip ancora più spettacolare. "
 }

#####

DELETE http://localhost:4040/BlogPosts/6410c1d8fa82f861c63abbb8


#####

GET http://localhost:4040/author?name=Armando

#####

GET http://localhost:4040/BlogComments/

#####

POST  http://localhost:4040/BlogComments/640f71e3bea275c3f3b27013 HTTP/1.1
Content-Type: application/json

{
"_id": "641206f5db32a284b81fc8fb",
"author": "anddgfgs Paolucci",
"comment": "Primo commento di adfgdfaprova",
"rate": 4,
"blogpostId": "641206f5db32a284b81fc8fb"
}

#####

PATCH http://localhost:4040/BlogComments/6419d5b2f2b13bdcdb37de3a
content-type: application/json

{
"author": "Gianluca Gianluchy",
"comment": "Secondo commento di prova aggiornato con Patch",
"blogpostId": {
  "_id": "640f71e3bea275c3f3b27013",
  "title": "L'iPhone migliore di sempre"
}
 }

 #####

DELETE http://localhost:4040/BlogComments/6419da119fee9974cb1bfa71